const $=s=>document.querySelector(s);
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label){for(let i=0;i<120;i++){if(fn())return;await pause(50);}throw Error('Timeout: '+label);}
const check=(condition,label)=>{if(!condition)throw Error(label);};
await until(()=>window.Galpi&&$('#note-title').value.includes('환영'),'initial note');
check(document.querySelectorAll('#editor input[type=checkbox]').length===3,'Markdown task list import');
check([...document.querySelectorAll('#editor input[type=checkbox]')].every(c=>!c.checked),'Unchecked tasks must stay unchecked');
$('#create').click();
await until(()=>$('#note-title').value===''&&document.querySelectorAll('.note-item').length===2,'new note');
$('#note-title').value='한글 메모 📝';$('#note-title').dispatchEvent(new Event('input',{bubbles:true}));
const body=$('#editor .tiptap');body.focus();
document.execCommand('insertText',false,'메모 본문 테스트');
await window.Galpi.flushAsync();
check(body.textContent==='메모 본문 테스트','Korean editor input');
$('#block-add').click();check(!$('#block-menu').hidden,'Block menu');
$('[data-block=task]').click();
await pause(100);
check(!!$('#editor input[type=checkbox]'),'Task block creation');
$('#editor input[type=checkbox]').click();
await window.Galpi.flushAsync();
check($('#editor input[type=checkbox]').checked,'Task checkbox toggle');
$('[data-tab=transcript]').click();
await until(()=>!!$('[data-tab=transcript].selected'),'transcript tab');
$('#editor .tiptap').focus();document.execCommand('insertText',false,'회의 전사 테스트');
await window.Galpi.flushAsync();
$('[data-tab=memo]').click();
await until(()=>!!$('[data-tab=memo].selected'),'memo tab');
check($('#editor .tiptap').textContent.includes('메모 본문 테스트'),'Memo preserved across tabs');
check($('#editor input[type=checkbox]').checked,'Checkbox state persisted');
$('#note-pin').click();await until(()=>$('#note-pin').getAttribute('aria-pressed')==='true','pin');
$('#compact').click();await until(()=>document.body.classList.contains('is-compact'),'compact');
$('#compact').click();await until(()=>!document.body.classList.contains('is-compact'),'expanded');
$('#trash').click();await until(()=>$('#note-title').value.includes('환영')&&!Array.from(document.querySelectorAll('.note-item')).some(n=>n.textContent.includes('한글 메모')),'archive');
$('#trash-view').click();await until(()=>$('#note-title').value==='한글 메모 📝','archive view');
$('#trash').click();await until(()=>$('#note-page').hidden&&!Array.from(document.querySelectorAll('.note-item')).some(n=>n.textContent.includes('한글 메모')),'restore');
$('#trash-view').click();await until(()=>!$('#note-page').hidden&&$('#note-title').value==='한글 메모 📝'&&!$('#record-open').disabled,'restored note');
$('#record-open').click();check(!$('#record-dialog').hidden,'Recording options');
check($('input[value=online]')&&$('input[value=inperson]'),'Both recording modes');
$('#record-cancel').click();
$('#create').click();
await until(()=>$('#note-title').value==='','new code note');
$('#note-title').value='코드 색상 테스트';$('#note-title').dispatchEvent(new Event('input',{bubbles:true}));
$('#editor .tiptap').focus();
$('#block-add').click();$('[data-block=code]').click();
await until(()=>!!$('.code-language'),'code language picker');
const js='// Galpi code sample\nconst message = "Hello, Galpi";\nfunction greet(name) {\n  return `${message} ${name}`;\n}\ngreet("Swift");';
await pause(100);
const clipboard=new DataTransfer();clipboard.setData('text/plain',js);
$('#editor .tiptap').dispatchEvent(new ClipboardEvent('paste',{clipboardData:clipboard,bubbles:true,cancelable:true}));
await until(()=>!!$('#editor pre .hljs-keyword'),'automatic syntax highlighting');
function language(value){const select=$('.code-language');select.value=value;select.dispatchEvent(new Event('change',{bubbles:true}));}
language('javascript');
await until(()=>!!$('#editor code.language-javascript .hljs-string'),'explicit JavaScript highlighting');
check($('#editor pre code').textContent===js,'Code text must be preserved');
language('plaintext');
await until(()=>!$('#editor pre [class*=hljs-]'),'plain text disables highlighting');
check($('#editor pre code').textContent===js,'Plain text switch must preserve content');
async function replaceCode(text){
  $('#editor .tiptap').focus();
  const range=document.createRange();range.selectNodeContents($('#editor pre code'));
  const selection=getSelection();selection.removeAllRanges();selection.addRange(range);
  await pause(50);
  const data=new DataTransfer();data.setData('text/plain',text);
  $('#editor .tiptap').dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));
}
const python='def greet(name):\n    return "안녕하세요, " + name';
await replaceCode(python);language('python');
await until(()=>!!$('#editor code.language-python .hljs-keyword'),'Python syntax highlighting');
check($('#editor pre code').textContent===python,'Python indentation and Korean strings preserved');
const swift='let message = "Hello, Galpi"\nprint(message)';
await replaceCode(swift);language('swift');
await until(()=>!!$('#editor code.language-swift .hljs-keyword'),'Swift syntax highlighting');
await replaceCode(js);
language('javascript');
await window.Galpi.flushAsync();
$('[data-tab=transcript]').click();await until(()=>!!$('[data-tab=transcript].selected'),'code transcript tab');
$('[data-tab=memo]').click();await until(()=>!!$('#editor code.language-javascript .hljs-keyword'),'code reload');
check($('.code-language').value==='javascript'&&$('#editor pre code').textContent===js,'Language and code roundtrip');
$('#trash').click();await until(()=>$('#note-title').value!=='코드 색상 테스트','archive code note');
$('#trash-view').click();await until(()=>$('#note-title').value==='코드 색상 테스트','archived code note');
check($('.code-language').disabled,'Archived code language is read only');
$('#trash').click();await until(()=>$('#note-page').hidden,'restore code note');
$('#trash-view').click();await until(()=>$('#note-title').value==='코드 색상 테스트'&&!$('.code-language').disabled,'restored code note');
$('#settings-open').click();check(!$('#settings').hidden,'Settings');
$('[data-settings=appearance]').click();
$('[data-theme-choice=dark]').click();await until(()=>document.documentElement.dataset.themeId==='dark','dark theme');
check(getComputedStyle(document.body).backgroundColor==='rgb(34, 34, 34)','Dark colors rendered');
const darkKeyword=getComputedStyle($('#editor .hljs-keyword')).color;
check(darkKeyword!==getComputedStyle($('#editor pre code')).color,'Dark syntax color is distinct');
check(getComputedStyle($('#editor .hljs-keyword')).color!==getComputedStyle($('#editor .hljs-string')).color,'Keyword and string colors differ');
$('#theme-new').click();$('#theme-name').value='미드나이트 테스트';$('#theme-name').dispatchEvent(new Event('input',{bubbles:true}));
const paper=$('#theme-hex-paper');paper.value='#142033';paper.dispatchEvent(new Event('input',{bubbles:true}));
check(getComputedStyle($('#theme-preview')).backgroundColor==='rgb(20, 32, 51)','Theme draft preview');
check(getComputedStyle(document.body).backgroundColor==='rgb(34, 34, 34)','Draft must not alter saved appearance');
$('#theme-save').click();await until(()=>$('#theme-dialog').hidden&&!!$('.custom-theme-card'),'custom theme saved');
check(getComputedStyle(document.body).backgroundColor==='rgb(20, 32, 51)','Custom theme applied');
const themeID=$('.custom-theme-card').dataset.themeId;
$('#theme-new').click();$('#theme-name').value='취소할 테마';$('#theme-name').dispatchEvent(new Event('input',{bubbles:true}));
$('#theme-cancel').click();check(document.querySelectorAll('.custom-theme-card').length===1,'Cancelled draft must not persist');
$('[data-theme-edit]').click();$('#theme-name').value='미드나이트 수정';$('#theme-name').dispatchEvent(new Event('input',{bubbles:true}));
$('#theme-save').click();await until(()=>$('#theme-dialog').hidden&&$('.theme-name').textContent==='미드나이트 수정','theme edit');
check($('.custom-theme-card').dataset.themeId===themeID,'Edit must preserve theme identity');
$('[data-theme-choice=light]').click();await until(()=>document.documentElement.dataset.themeId==='light','switch back to light');
check(getComputedStyle(document.body).backgroundColor==='rgb(255, 254, 253)','Custom colors cleared for built-in themes');
check(getComputedStyle($('#editor .hljs-keyword')).color!==darkKeyword,'Code palette follows light theme');
$('.custom-theme-choice').click();await until(()=>document.documentElement.dataset.themeId===themeID,'custom theme reselected');
$('[data-settings=ai]').click();
check($('#ai-provider').value==='chatgpt'&&!$('#chatgpt-settings').hidden&&$('#claude-settings').hidden,'Legacy AI selection remains ChatGPT');
$('#ai-provider').value='claude';$('#ai-provider').dispatchEvent(new Event('change',{bubbles:true}));
await until(()=>!$('#claude-settings').hidden&&$('#chatgpt-settings').hidden,'Claude provider panel');
await until(()=>$('#claude-sign-in').disabled&&$('#claude-status').textContent.includes('설치'),'Missing CLI offers installation without reading real credentials');
check($('#summary-provider-hint').textContent.includes('Claude'),'Summary destination follows provider');
$('#claude-model').value='opus';$('#claude-model').dispatchEvent(new Event('change',{bubbles:true}));
await pause(150);
$('#ai-provider').value='chatgpt';$('#ai-provider').dispatchEvent(new Event('change',{bubbles:true}));
await until(()=>!$('#chatgpt-settings').hidden,'Switch back to ChatGPT');
$('#ai-provider').value='claude';$('#ai-provider').dispatchEvent(new Event('change',{bubbles:true}));
await until(()=>!$('#claude-settings').hidden&&$('#claude-model').value==='opus','Claude model preserved across provider switch');
$('#settings-close').click();
await window.Galpi.flushAsync();
return 'Korean notes, autosave, archive/restore, code highlighting/language/persistence/read-only state and custom themes passed';
